   00037F7F333333337F7F000FFFFFFFFF00037F7F333333337F7F000FFFFFFFFF
        00037F7F333333337F7F000FFFFFFFFF00037F7F333333337F7F000FFFFFFFFF
        00037F7F333333337F7F000FFFFFFFFF07037F7F33333333777F000FFFFFFFFF
        0003737FFFFFFFFF7F7330099999999900333777777777777733}
      NumGlyphs = 2
    end
    object BitBtn3: TBitBtn
      Left = 472
      Top = 8
      Width = 105
      Height = 41
      Caption = 'Tutup Stok'
      TabOrder = 4
      OnClick = BitBtn3Click
    end
    object LMDProgress1: TProgressBar
      Left = 1
      Top = 52
      Width = 1026
      Height = 17
      Align = alBottom
      Smooth = True
      TabOrder = 5
    end
    object BitBtn4: TBitBtn
      Left = 368
      Top = 8
      Width = 91
      Height = 41
      Caption = 'Update Mutasi'
      TabOrder = 6
      OnClick = BitBtn4Click
    end
    object wwDBDateTimePicker1: TwwDB