7F77777777777F7F000FFFFFFFFF
              00037F7F333333337F7F000FFFFFFFFF00037F7F333333337F7F000FFFFFFFFF
              00037F7F333333337F7F000FFFFFFFFF00037F7F333333337F7F000FFFFFFFFF
              00037F7F333333337F7F000FFFFFFFFF07037F7F33333333777F000FFFFFFFFF
              0003737FFFFFFFFF7F7330099999999900333777777777777733}
            NumGlyphs = 2
          end
        end
      end
      object wwDBGrid2: TwwDBGrid
        Left = 0
        Top = 52
        Width = 872
        Height = 460
        DisableThemes = True
        DisableThemesInTitle = True
        Selected.Strings = (
          'KONSTRUKSI'#9'24'#9'Konstruksi'#9'F'#9'PALEKAT'
          'CORAK'#9'17'#9'Corak'#9'F'#9'PALEKAT'
          'KODI_BK'#9'10'#9'Kode'#9'F'#9'BK'
          'PCS_BK'#9'10'#9'Pcs'#9'F'#9'BK'
          'KODI_BS'#9'10'#9'Kodi'#9'F'#9'BS'
          'PCS_BS'#9'10'#9'Pcs'#9'F'#9'BS'
          'KODI_BS_PARAH'#9'10'#9'Kodi'#9'F'#9'PARAH'
          'PCS_BS_PARAH'#9'10'#9'Pcs'#9'F'#9'PARAH')
        IniAttributes.Enabled = True
        IniAttributes.SaveToRegistry = True
        IniAttributes.FileName = 'Pismatex Master'
        IniAttributes.Delimiter = ';;'
        IniAttributes.CheckNewFields = True
        ExportOptions.ExportType = wwgetSYLK
        ExportOptions.Options = [esoShowHeader, esoShowTitle, esoDblQuoteFields, esoBestColFit, esoShowAlternating]
        TitleColor = clSkyBlue
        FixedCols = 0
        ShowHorzScrollBar = True
        Align = alClient
        DataSource = dsQBrowse2
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'MS Sans Serif'
        Font.Style = []
        Options = [dgEditing, dgTitles, dgIndicator, dgColumnResize, dgColLines, dgTabs, dgRowSelect, dgConfirmDelete, dgCancelOnExit, dgPerfectRowFit, dgShowFooter, dgTrailingEllipsis, dgDblClickColSizing]
        ParentFont = False
        ReadOnly = True
        RowHeightPercent = 125
        TabOrder