
            Height = 19
            Color = clWhite
            DataField = 'DIM_P'
            DataSource = dsCDSMaster
            TabOrder = 2
            UnboundDataType = wwDefault
            WantReturns = False
            WordWrap = False
          end
          object wwDBEdit20: TwwDBEdit
            Left = 376
            Top = 24
            Width = 41
            Height = 19
            Color = clWhite
            DataField = 'DIM_L'
            DataSource = dsCDSMaster
            TabOrder = 3
            UnboundDataType = wwDefault
            WantReturns = False
            WordWrap = False
          end
          object wwDBEdit2: TwwDBEdit
            Left = 520
            Top = 11
            Width = 57
            Height = 19
            Color = clWhite
            DataField = 'NSISIR'
            DataSource = dsCDSMaster
            TabOrder = 6
            UnboundDataType = wwDefault
            WantReturns = False
            WordWrap = False
          end
          object wwDBEdit4: TwwDBEdit
            Left = 576
            Top = 11
            Width = 57
            Height = 19
            Color = clWhite
            DataField = 'NPICK'
            DataSource = dsCDSMaster
            TabOrder = 7
            UnboundDataType = wwDefault
            WantReturns = False
            WordWrap = False
          end
          object wwDBEdit5: TwwDBEdit
            Left = 576
            Top = 66
            Width = 57
            Height = 19
            Color = 13421823
            DataField = 'NPAKAN'
            DataSource = dsCDSMaster
            TabOrder = 15
            UnboundDataType = wwDefault
            WantReturns = False
            WordWrap = False
          end
          object wwDBEdit6: TwwDBEdit
            Left = 520
            Top = 66
            Width = 57
            Height = 19
            Color = 13421823
            DataField = 'NLUSI_ORG'
            DataSource = dsCDSMaster
            TabOrder = 16
            UnboundDataType = wwDefault
            WantReturns = False
            WordWrap = False
          end
          object wwDBEdit8: TwwDBEdit
            Left = 520
            Top = 84
            Width =