Width = 121
        Height = 21
        Options = [opShowOKCancel, opShowSearchBy, opShowStatusBar]
        GridOptions = [dgTitles, dgIndicator, dgColumnResize, dgColLines, dgRowLines, dgTabs, dgRowSelect, dgAlwaysShowSelection, dgConfirmDelete, dgPerfectRowFit]
        GridColor = clWhite
        GridTitleAlignment = taLeftJustify
        Caption = 'Lookup'
        MaxWidth = 0
        MaxHeight = 209
        UserButton1Caption = '&Refresh'
        UserButton2Caption = 'Urut Kode'
        OnUserButton1Click = LookItemUserButton1Click
        OnUserButton2Click = LookItemUserButton2Click
        Selected.Strings = (
          'NAMA_ITEM'#9'40'#9'NAMA_ITEM'#9'F'#9
          'KD_ITEM'#9'10'#9'KODE'#9'F'#9
          'NO_PART'#9'12'#9'NO_PART'#9'F'#9
          'SAT1'#9'12'#9'SATUAN'#9'F'
          'KELOMPOK'#9'30'#9'KELOMPOK'#9'F'
          'STOK'#9'6'#9'STOK'#9'F')
        DataField = 'KD_ITEM'
        DataSource = dsQDetail
        LookupTable = QLookItem
        LookupField = 'KD_ITEM'
        TabOrder = 5
        AutoDropDown = False
        ShowButton = True
        AllowClearKey = False
        OnCloseUp = LookItemCloseUp
        OnEnter = LookItemEnter
      end
    end
    object TabSheet3: TTabSheet
      Caption = 'Analisa Transaksi yang tidak 